#!/usr/bin/env python

import os
import sys
import subprocess
import optparse

ALIASES = [
    ('r', 'runserver'),
    ('s', 'shell'),
]

try:
    command = sys.argv[1]
except IndexError:
    os.system('%s manage.py' % sys.executable)
else:
    for alias in ALIASES:
        if alias[0] == command:
            command = alias[1]

    os.system('%s manage.py %s %s' % (sys.executable, command, ' '.join(sys.argv[2:])))
